### ISSUE TITLE
Feature request: moonstick

### ISSUE THREAD

**Issue by rcomer** [bjlittle/stale#21]
Please provide the moon on a stick in the next release 👍

**Comment by bjlittle** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/2051656/120873595-a5aac600-c59a-11eb-956e-da96d041c06d.png)

**Comment by rcomer** [comment]
@bjlittle awesome! 😀

**Comment by rcomer** [comment]
Closing is not acceptable.  I need my moonstick!

**Comment by bjlittle** [comment]
If you insist. I'll pass your issue request onto the Celestial Dev Group.

I'm sure they'll be in your orbit soon. But please be aware, they are busy eating cheese at the moment.

**Comment by rcomer** [comment]
😭
