### ISSUE TITLE
Micropachycephalosaurus

### ISSUE THREAD

**Issue by trexfeathers** [bjlittle/stale#25]
🦖

**Comment by trexfeathers** [comment]
I do not have permission to re-open this myself, if that's useful information?

**Comment by rcomer** [comment]
Maybe that's for the best: if someone wants to to resurrect an issue after a long time, it could be cleaner to open a new issue with up-to-date information.  Particularly if the old issue's scope had creeped, as they sometimes do.

**Comment by trexfeathers** [comment]
>it could be cleaner to open a new issue with up-to-date information

Oooh that's a new take that I don't remember in the original discussion. I could get behind it.

**Comment by bjlittle** [comment]
@rcomer Either that, or they @ the devs to alert them to re-open the issue. That can be clarified in closing message from the bot.

**Comment by bjlittle** [comment]
I'm personally fine with that as a workflow 👍

**Comment by rcomer** [comment]
@bjlittle sounds reasonable to me.
